strains:

  - name: secure-dashboard
    condition:
      url: https://main--dcit-eds--shubhanshu23.aem.page/dashboard
    redirects:
      - from: /dashboard
        to: https://your-middleware-host/login-check?next=/dashboard
