strains:
  - name: secure-dashboard
    urls:
      hostname: main--dcit-eds--shubhanshu23.aem.page
      pathname: /dashboard
    redirects:
      - from: /dashboard
        to: https://main--dcit-eds--middleware.aio.app/api/v1/web/eds-middleware/login-check?next=/dashboard

  - name: auth-callback
    urls:
      hostname: main--dcit-eds--shubhanshu23.aem.page
      pathname: /auth/callback

  - name: default
    urls:
      hostname: main--dcit-eds--shubhanshu23.aem.page
